name: Build Everything On Demand

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   
    container: 
      image: hkershaw/dart-dep:1.0
      options: "--cap-add=SYS_PTRACE"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set to safe directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      
      - name: Create mkmf.template
        run: |
          # echo "RTTOV version ${{ github.event.inputs.rttov_version }}"
          cp build_templates/mkmf.template.gfortran build_templates/mkmf.template

      - name: Run fixsystem
        run: |
          export DART=$(git rev-parse --show-toplevel)
          cd $DART/assimilation_code/modules/utilities
          ./fixsystem gfortran
          cd -

      - name: Modify input.nml files
        run: |
          find $DART -name input.nml -exec sed -i -e "/^[[:space:]]*#/! s|.*output_obs_def_mod_file.*|output_obs_def_mod_file = './obs_def_mod.f90'|g" \
            -e "/^[[:space:]]*#/! s|.*output_obs_qty_mod_file.*|output_obs_qty_mod_file = './obs_kind_mod.f90'|g" \
            -e "/^[[:space:]]*#/! s|.*output_obs_kind_mod_file.*|output_obs_qty_mod_file = './obs_kind_mod.f90'|g" {} \;

      - name: Run quickbuild.sh scripts
        run: |
          find $DART -executable -type f -name quickbuild.sh | while read qb; do
            (cd "$(dirname "$qb")" && ./quickbuild.sh) || echo "FAILED: $qb" >> $GITHUB_WORKSPACE/quickbuild-failures.txt
          done
      
      - name: Report Failures
        run: |
          if [ -f $GITHUB_WORKSPACE/quickbuild-failures.txt ]; then
            echo "Failed builds:"
            cat $GITHUB_WORKSPACE/quickbuild-failures.txt
            exit 1
          else
            echo "All runs passed"
          fi
